const  INCREMENT='INCREMENT';
const  DECREMENT='DECREMENT';
const ADD_INC='ADD_INC';
const SUB_DEC='SUB_DEC';
const UPDATE='UPDATE';
const DELETE='DELETE';


export {INCREMENT,DECREMENT,ADD_INC,SUB_DEC,UPDATE,DELETE};